FROM node:18-alpine

WORKDIR /app

# 配置 npm 使用淘宝镜像源
RUN npm config set registry https://registry.npmmirror.com

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

ENV NODE_ENV=production

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]
